added healthcheck for reviewer service
Fidel1985/ReviewerRoot pull request #9
Opened 2016-10-27 11:24 UTC by Fidel1985

2016-10-28 13:15 UTC, svoronin requested changes
Overall I think that we don't need entities for healthcheck responses. We should be fine with checking HTTP code responses. If that is 200, we consider related service as healthy. Otherwise we consider it down or unavailable (if responses take too long). Also I think we can have only one common implementation for such HealthCheck and instantiate it for every downstream service with proper healthCheckURL.

2016-10-28 13:15 UTC, svoronin commented on DataProviders/src/main/java/com/softserveinc/reviewer/health/ElasticSearchHealthCheck.java
> +        //return Result.unhealthy("something went wrong");
Please remove that comment

2016-10-28 14:44 UTC, Fidel1985 commented
If we would check only response codes, in case when one of the services is unhealthy, the hole response would have status code 500 (Server Error). So I created that entities to localize unheathy service.

2016-10-28 15:38 UTC, svoronin commented
I think it is legit to return 503 in case any of the downstream services is not working properly

2016-10-28 15:39 UTC, svoronin commented on Reviewer/configuration.yaml
> +syndicationAdminBaseUrl: http://localhost:8085
I'd better call it ***HealthcheckUrl

2016-11-01 12:05 UTC, svoronin approved these changes

2016-11-01 12:05 UTC, svoronin commented on Reviewer/src/main/java/com/softserveinc/reviewer/health/DataProvidersHealthCheck.java
> +        URL url = new URL(healthCheckUrl + "/healthcheck");
```/health``` should be part of field value in configuration

2016-11-01 12:05 UTC, svoronin commented on Reviewer/src/main/java/com/softserveinc/reviewer/ReviewerApplication.java
> +        environment.healthChecks().register("ElasticSearchHealthCheck", new DataProvidersHealthCheck(configuration.getElasticSearchHealthCheckUrl()));
Please change it to be switchboard, oracle and elasticsearch respectively. No need to call it health check explicitly.

2016-11-01 12:13 UTC, merged